title: Nick Crawford
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nick Crawford # add your name
author-img: nick.png # add your photo
about-author: Driven and curious software engineer. Incredibly interested in AR/VR, Python, Web, and Mobile and more. # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: nighthawk469 # add your Github handle
linkedin: nickdcrawford # add your Linkedin handle
email: nick.crawford1234@gmail.com # add your Email address

# Disqus
# discus-identifier: # add your discus identifier

# Tracker
analytics: UA-86540206-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
